version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify the Node.js version
    commands:
      - echo "Installing Node.js version 18..."
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*' # Include all files to ensure `node_modules` is included
  discard-paths: no
