version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 14..."
      - n 14
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*' # Include all files to ensure `node_modules` is included
  discard-paths: no
