version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 14..."
      - n 14
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'build/**/*'
    - 'node_modules/**/*'
    - 'package.json'
    - 'package-lock.json'

cache:
  paths:
    - 'node_modules/**/*'
