version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running lint and tests...
      - npm run lint
      - npm test

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
