steps:
- name: 'node:18'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Installing Node.js version 18..."
    npm install -g npm@latest
    npm cache clean --force
    echo "Preparing for clean install..."
    rm -rf node_modules
    rm -f package-lock.json
    echo "Installing dependencies..."
    npm install

- name: 'node:18'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Running tests..."
    CI=true npm test -- --watchAll=false --forceExit --detectOpenHandles || exit 1

- name: 'node:18'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Building the application..."
    npm run build

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'build/*', 'gs://dimitar_bucket/']

images: []
artifacts:
  objects:
    location: 'gs://dimitar_bucket/'
    paths: ['build/**']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
